# Generated by Django 5.0.6 on 2024-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
